# Generated by Django 6.0.2 on 2026-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessresource',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessresource',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
